print("Calling write with non-nil")
write("hey")
print("Calling write with nil")
write(nil)

print("Calling process with non-nil")
process(4)
print("Calling process with nil")
process(nil)

print("Calling abs with -1")
print(abs(-1))
print("Calling abs with nil")
print(abs(nil) ?? "nil")
print("Calling abs with 5")
print(abs(5))
